"""Add chat and quiz models

Revision ID: 4c655af99a1b
Revises: 
Create Date: 2026-02-15 17:12:12.073965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c655af99a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_table('quiz_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('question_hash', sa.String(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_items_session_id'), 'quiz_items', ['session_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_project_id'), 'quiz_sessions', ['project_id'], unique=False)
    op.drop_table('assets')
    op.drop_table('results')
    op.drop_table('llm_active')
    op.drop_table('llm_profile_secrets')
    op.add_column('jobs', sa.Column('output_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'output_language')
    op.create_table('llm_profile_secrets',
    sa.Column('provider_id', sa.VARCHAR(), nullable=False),
    sa.Column('ciphertext', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at_ms', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('llm_active',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), nullable=False),
    sa.Column('model_id', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at_ms', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_llm_active_singleton')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('result_id', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.TEXT(), nullable=False),
    sa.Column('schema_version', sa.TEXT(), nullable=False),
    sa.Column('pipeline_version', sa.TEXT(), nullable=False),
    sa.Column('created_at_ms', sa.INTEGER(), nullable=False),
    sa.Column('updated_at_ms', sa.INTEGER(), nullable=False),
    sa.Column('content_blocks', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('mindmap', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('note_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('asset_refs', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('origin', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('chapter_id', sa.VARCHAR(), nullable=True),
    sa.Column('time_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at_ms', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.drop_index(op.f('ix_quiz_sessions_project_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_quiz_items_session_id'), table_name='quiz_items')
    op.drop_table('quiz_items')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
